# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-02 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvoidItUser',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('LO', 'Location'), ('CA', 'Category'), ('PR', 'Price')], max_length=2)),
                ('category_specs', models.CharField(max_length=2000)),
                ('alert_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('rid', models.IntegerField(primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=30)),
                ('passes', models.IntegerField()),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avoid.AvoidItUser')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avoid.Rule'),
        ),
        migrations.AddField(
            model_name='contactlist',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avoid.Rule'),
        ),
    ]
